#!/bin/sh
ver=$(cat version)
case $1 in
	start)
		if [ ! -f pyserv.pid ]; then
			rm -f commands/*.pyc
			if [ -f pyserv.pyc ]; then
				rm -f pyserv.pyc
			fi
			python pyserv.py >> /dev/null &
			pid=$!
			echo $pid > pyserv.pid
			echo "PyServ ($ver) started into background (PID: $pid)"
		else
			pid=$(cat pyserv.pid)
			status="false"
			for data in $(ps | grep $pid); do
				status="true"
			done
			if [ $status = "false" ]; then
				rm -f pyserv.pid
				sh pyserv start
			else
				echo "PyServ ($ver) is already running"
			fi
		fi
		;;
	stop)
		if [ -f pyserv.pid ]; then
			pid=$(cat pyserv.pid)
			kill -9 $pid
			rm -f pyserv.pid
			rm -f commands/*.pyc
			if [ -f pyserv.pyc ]; then
				rm -f pyserv.pyc
			fi
			echo "PyServ ($ver) is stopped (PID: $pid)"
		else
			echo "PyServ ($ver) is not running"
		fi
		;;
	restart)
		if [ -f pyserv.pid ]; then
			sh pyserv stop
			sh pyserv start
		else
			sh pyserv start
		fi
		;;
	debug)
		while [ 1 ]; do
			if [ -f pyserv.pyc ]; then
				rm -f pyserv.pyc
			fi
			rm -f commands/*.pyc
			python pyserv.py
			rm -f commands/*.pyc
			if [ -f pyserv.pyc ]; then
				rm -f pyserv.pyc
			fi
		done
		;;
	update)
		available=$(curl https://raw.github.com/Pythonz/PyServ/master/version)
		version=$(cat version)
		if [ $available != $version ]; then
			running="false"
			if [ -f pyserv.pid ]; then
				sh pyserv stop
				running="true"
			fi
			git rm commands/*.pyc
			git add .
			git commit -m 'Save'
			git pull
			if [ $running = "true" ]; then
				sh pyserv start
			fi
			echo "Done."
		else
			echo "No update available."
		fi
		;;
	status)
		if [ -f pyserv.pid ]; then
			pid=$(cat pyserv.pid)
			status="PyServ ($ver) seems to be crashed"
			for data in $(ps | grep $pid); do
				status="PyServ ($ver) is running"
			done
		else
			status="PyServ ($ver) is not running"
		fi
		echo $status
		;;
	*)
		echo "start | stop | restart | debug | update | status"
		;;
esac
	
